name: Cleanup Old Workflows

on:
  schedule:
    - cron: '0 0 * * 0'  
  workflow_dispatch:  

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      actions: write  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete old workflows
        run: |
          
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"

          TWO_WEEKS_AGO=$(date -u --date="2 weeks ago" +"%Y-%m-%dT%H:%M:%SZ")
          echo "Deleting workflows older than: $TWO_WEEKS_AGO"

          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100")

          for run_id in $(echo $WORKFLOW_RUNS | jq -r --arg date "$TWO_WEEKS_AGO" '.workflow_runs[] | select((.status == "completed" or .status == "failed") and .created_at < $date) | .id'); do
            echo "Deleting workflow run: $run_id"
            curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done
