name: Cleanup Old Workflows

on:
  schedule:
    - cron: '0 0 * * 0'  
  workflow_dispatch:  

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete old workflows
        run: |
          
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"

          
          WORKFLOW_RUNS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs")

          
          for run_id in $(echo $WORKFLOW_RUNS | jq -r '.workflow_runs[] | select(.status == "completed" and .created_at < "2025-01-01T00:00:00Z") | .id'); do
            echo "Deleting workflow run: $run_id"
            curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id"
          done
