name: Build Egern blocklist

on:
  schedule:
    - cron: "0 2 * * 1"  # Thứ 2, 02:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Convert to YAML (Egern)
        run: |
          python convert_egern.py

      - name: Commit changes if any
        run: |
          set -e
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if git status --porcelain | grep -q "docs/blocklist.yml"; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/blocklist.yml
            git commit -m "chore: update egern blocklist [skip ci]"
            git fetch origin main
            git rebase origin/main
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          else
            echo "No changes to commit."
          fi
